from enum import Enum

class Aisle(Enum):
    BAKING = "Baking"
    HEALTH_FOODS = "Health Foods"
    SPICES_AND_SEASONINGS = "Spices and Seasonings"
    PASTA_AND_RICE = "Pasta and Rice"
    BAKERY_BREAD = "Bakery/Bread"
    REFRIGERATED = "Refrigerated"
    CANNED_AND_JARRED = "Canned and Jarred"
    FROZEN = "Frozen"
    NUT_BUTTERS_JAMS_HONEY = "Nut butters, Jams, and Honey"
    OIL_VINEGAR_SALAD_DRESSING = "Oil, Vinegar, Salad Dressing"
    CONDIMENTS = "Condiments"
    SAVORY_SNACKS = "Savory Snacks"
    MILK_EGGS_OTHER_DAIRY = "Milk, Eggs, Other Dairy"
    ETHNIC_FOODS = "Ethnic Foods"
    TEA_AND_COFFEE = "Tea and Coffee"
    MEAT = "Meat"
    GOURMET = "Gourmet"
    SWEET_SNACKS = "Sweet Snacks"
    GLUTEN_FREE = "Gluten Free"
    ALCOHOLIC_BEVERAGES = "Alcoholic Beverages"
    CEREAL = "Cereal"
    NUTS = "Nuts"
    BEVERAGES = "Beverages"
    PRODUCE = "Produce"
    NOT_IN_GROCERY_STORE_HOMEMADE = "Not in Grocery Store/Homemade"
    SEAFOOD = "Seafood"
    CHEESE = "Cheese"
    DRIED_FRUITS = "Dried Fruits"
    ONLINE = "Online"
    GRILLING_SUPPLIES = "Grilling Supplies"
    BREAD = "Bread"
