from enum import Enum

class Cuisine(Enum):
    AFRICAN = "african"
    ASIAN = "asian"
    AMERICAN = "american"
    BRITISH = "british"
    CAJUN = "cajun"
    CARIBBEAN = "caribbean"
    CHINESE = "chinese"
    EASTERN_EUROPEAN = "eastern european"
    EUROPEAN = "european"
    FRENCH = "french"
    GERMAN = "german"
    GREEK = "greek"
    INDIAN = "indian"
    IRISH = "irish"
    ITALIAN = "italian"
    JAPANESE = "japanese"
    JEWISH = "jewish"
    KOREAN = "korean"
    LATIN_AMERICAN = "latin american"
    MEDITERRANEAN = "mediterranean"
    MEXICAN = "mexican"
    MIDDLE_EASTERN = "middle eastern"
    NORDIC = "nordic"
    SOUTHERN = "southern"
    SPANISH = "spanish"
    THAI = "thai"
    VIETNAMESE = "vietnamese"
